// Argon2id master key derivation using @noble/hashes
// Parameters must match Argon2::default() in the Rust argon2 crate:
//   t_cost=2, m_cost=19456, p_cost=1, output=32 bytes
//
// VITE_MASTER_SALT_HEX must be set to the hex of ~/.config/solidrop/master.salt
// (generated by `solidrop init`). The salt is NOT secret.

import { argon2id } from '@noble/hashes/argon2'

const ARGON2_PARAMS = { t: 2, m: 19456, p: 1, dkLen: 32 } as const

function getMasterSalt(): Uint8Array {
  const hex = import.meta.env.VITE_MASTER_SALT_HEX as string | undefined
  if (!hex || hex.length !== 32) {
    throw new Error(
      'VITE_MASTER_SALT_HEX is not configured or invalid. ' +
      'Run `solidrop init`, read the salt at ~/.config/solidrop/master.salt, ' +
      'and set VITE_MASTER_SALT_HEX=<32-char hex> in your build environment.'
    )
  }
  const bytes = new Uint8Array(16)
  for (let i = 0; i < 16; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

/**
 * Derive the 32-byte master key from the user's password using Argon2id.
 * This is CPU-intensive (~500ms–2s). Consider running in a Web Worker for production.
 */
export function deriveMasterKey(password: string): Uint8Array {
  const salt = getMasterSalt()
  const enc = new TextEncoder()
  return argon2id(enc.encode(password), salt, ARGON2_PARAMS)
}
